spring:
  datasource:
    password: srivatsan
    url: jdbc:mysql://localhost:3306/test
    username: root

    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: doctor-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka