
spring:
  datasource:
    password: srivatsan
    url: jdbc:mysql://localhost:3306/test
    username: root

    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: restaurant-service
        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
        
 
        