spring:
  datasource:
    password: srivatsan
    url: jdbc:mysql://localhost:3306/test
    username: root

    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl